definitions:
  internal_controller.UserResponse:
    properties:
      user:
        type: string
    type: object
info:
  contact: {}
  title: go template api
  version: "1.0"
paths:
  /public/api/v1/user:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_controller.UserResponse'
      summary: GetUser
      tags:
      - users
swagger: "2.0"
